# File: .github/workflows/OIDC_workflow.yml

name: Run Azure Login with OIDC
on: [push]

permissions:
      id-token: write
      contents: read
jobs:
  build-and-deploy:
    env:
     ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
     ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform fmt
        working-directory: ./container-registry
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        working-directory: ./container-registry
        id: init
        run: terraform init
      - name: Terraform Validate
        working-directory: ./container-registry
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        working-directory: ./container-registry
        id: plan
        run: terraform plan -out=plan.out
        continue-on-error: false
      - name: Terraform Apply
        working-directory: ./container-registry
        id: apply
        run: terraform apply -auto-approve plan.out